export default {
  id: "gemini",
  priority: 50,
  hasFree: true,
  alias: "gemini",
  display: {
    name: "Gemini",
    icon: "diamond",
    color: "#4285F4",
    textIcon: "GE",
    website: "https://ai.google.dev",
    notice: {
      apiKeyUrl: "https://aistudio.google.com/app/apikey",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  mediaPriority: 1,
  // Daily quotas reset at 10:00 Europe for every Gemini model (Google free tier)
  rateLimits: { rpdResetHour: 10 },
  transport: {
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/models",
    format: "gemini",
    auth: {
      apiKey: {
        header: "x-goog-api-key",
        scheme: "raw",
      },
      oauth: {
        header: "Authorization",
        scheme: "bearer",
      },
    },
  },
  models: [
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", rpm: 5, tpm: 250000, rpd: 20 },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash", rpm: 5, tpm: 250000, rpd: 20 },
    { id: "gemini-3.6-flash", name: "Gemini 3.6 Flash", rpm: 5, tpm: 250000, rpd: 20 },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", rpm: 5, tpm: 250000, rpd: 20 },
    { id: "gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite", rpm: 15, tpm: 250000, rpd: 500 },
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", rpm: 15, tpm: 250000, rpd: 500 },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview", rpm: 5, tpm: 250000, rpd: 20 },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite", rpm: 10, tpm: 250000, rpd: 20 },
    { id: "gemini-embedding-2", name: "Gemini Embedding 2", dimensions: 3072, kind: "embedding" },
    { id: "gemini-embedding-001", name: "Gemini Embedding 001", dimensions: 768, kind: "embedding" },
    { id: "gemini-3.1-flash-image-preview", name: "Gemini 3.1 Flash Image (Nano Banana 2)", params: [], kind: "image" },
    { id: "gemini-3-pro-image-preview", name: "Gemini 3 Pro Image (Nano Banana Pro)", params: [], kind: "image" },
    { id: "gemini-2.5-flash-image", name: "Gemini 2.5 Flash Image (Nano Banana)", params: [], kind: "image" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro (Best)", params: ["language","prompt"], kind: "stt" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", params: ["language","prompt"], kind: "stt" },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite (Cheapest)", params: ["language","prompt"], kind: "stt" },
    { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", params: ["language","prompt"], kind: "stt" },
    { id: "gemini-3.1-flash-tts-preview", name: "Gemini 3.1 Flash TTS", kind: "tts" },
    { id: "gemini-2.5-flash-preview-tts", name: "Gemini 2.5 Flash TTS", kind: "tts" },
    { id: "gemini-2.5-pro-preview-tts", name: "Gemini 2.5 Pro TTS", kind: "tts" },
  ],
  serviceKinds: ["llm","embedding","image","imageToText","webSearch","tts","stt"],
  ttsConfig: {
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/models",
    authType: "apikey",
    authHeader: "key",
    format: "gemini-tts",
  },
  sttConfig: {
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/models",
    authType: "apikey",
    authHeader: "key",
    format: "gemini-stt",
  },
  embeddingConfig: { baseUrl: "https://generativelanguage.googleapis.com/v1beta/models", authType: "apikey", authHeader: "key" },
  imageConfig: { baseUrl: "https://generativelanguage.googleapis.com/v1beta/models" },
  searchViaChat: {
    defaultModel: "gemini-2.5-flash",
    // Tried in order when the previous model is quota/rate exhausted (429 or quota error)
    fallbackModels: ["gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.6-flash"],
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
    pricingUrl: "https://ai.google.dev/pricing",
    freeTier: "Free tier: 15 RPM via AI Studio.",
  },
};
